### ISSUE TITLE
Error during exception handling: TypeError: sleep() got an unexpected keyword argument 'loop'

### ISSUE THREAD

**Issue by saschaludwig** [arturpragacz/hass-cc-onkyo-dev#1]
I just tried the dev integration and what I tried worked so far. Will try more things in the coming days.
However I encountered this error at some point in my log (most likely the receiver wasn't reachable at that point)
But during the error handling, another exception occurred:

=============
Logger: homeassistant
Source: custom_components/onkyo/media_player.py:225
Integration: Onkyo
Erstmals aufgetreten: 00:11:04 (1 Vorkommnisse)
Zuletzt protokolliert: 00:11:04

```
Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/pyeiscp/connection.py", line 350, in _reconnect
    await self._loop.create_connection(
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1122, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1104, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1007, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 641, in sock_connect
    return await fut
           ^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 681, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('192.168.44.1', 60128)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/onkyo/media_player.py", line 269, in async_onkyo_interview_callback
    await async_setup_receiver(info, False, name)
  File "/config/custom_components/onkyo/media_player.py", line 225, in async_setup_receiver
    connection = await pyeiscp.Connection.create(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyeiscp/connection.py", line 188, in create
    await conn._reconnect()
  File "/usr/local/lib/python3.12/site-packages/pyeiscp/connection.py", line 369, in _reconnect
    await asyncio.sleep(interval, loop=self._loop)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: sleep() got an unexpected keyword argument 'loop'
```

Please let me know if you need further information.

**Comment by arturpragacz** [comment]
Library had incorrectly structured imports. Re-download the integration and the issue should be fixed.
